# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amassnao <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/03 18:13:09 by amassnao          #+#    #+#              #
#    Updated: 2018/10/03 18:17:59 by amassnao         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all :
	gcc -Wall -Wextra -Werror srcs/* includes/*
	mv a.out ft_display_file
clean :
	rm -f src/*.o
	rm -f includes/*.gch
fclean : clean
	rm ft_display_file
